name: "Create release"
description: "Creates, tags and pushes a release commit as webredax. Includes uncommitted changes if there are any."
inputs:
  new_version:
    required: true
    description: "v*.*.* or patch/minor/major"
runs:
  using: "docker"
  image: "Dockerfile"
